Release/MvcRaamatuKogu/MvcRaamatuKogu/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcRaamatuKogu.Models;
using System.Collections.ObjectModel;
using System.Data;
using System.Web.Security;
using System.IO;
using System.Web.Helpers;

namespace MvcRaamatuKogu.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        RaamatuKoguEntities db = new RaamatuKoguEntities();

        //
        // GET: /Profile/
        public ActionResult Index()
        {
            if (Request.IsAuthenticated)
            {
                MembershipUser kasutaja = Membership.GetUser();
                Guid userID = (Guid)kasutaja.ProviderUserKey;
                string user = User.Identity.Name;
                var itemid = db.UserItems.Where(i => i.UserId == userID).ToList();
                return View(itemid);
            }
            return View();
        }

        #region KastuajaRaamatuHaldus
        //
        // GET: /Profile/Details/5
        public ActionResult Book(int id = 0)
        {
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);


        }
        //
        // GET: /Profile/LisaRaamat/
        public ActionResult LisaRaamat()
        {

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View();
        }

        //
        // POST: /Profile/LisaRaamat/
        [HttpPost]
        public ActionResult LisaRaamat(Item item)
        {
            MembershipUser kasutaja = Membership.GetUser();
            Guid userID = (Guid)kasutaja.ProviderUserKey;
            try
            {
                if (ModelState.IsValid)
                {
                    Autor autor = new Autor()
                    {
                        Perekonnanimi = item.Autors.Perekonnanimi
                    };
                    db.Autors.Add(autor);
                    db.SaveChanges();
                    var autorId = (from x in db.Autors
                                   where x.Perekonnanimi == item.Autors.Perekonnanimi
                                   select x.AutorId).FirstOrDefault();

                    item.Lisatud = DateTime.Now;
                    item.CoverArtUrl = "/UploadedImages/placeholder.gif";
                    item.AutorId = autorId;
                    db.Items.Add(item);
                    db.SaveChanges();


                    var itm = (from x in db.Items
                               where x.ItemId == item.ItemId
                               select x.ItemId).FirstOrDefault();
                    string _user = User.Identity.Name;

                    var kasutajaID = (from z in db.Kasutajad
                                      where z.fk_UserId == userID
                                      select z.KasutajaId).First();
                    UserItem userItem = new UserItem()
                    {
                        Adder = _user,
                        ItemId = itm,
                        UserId = userID,
                        Added = DateTime.Now,
                        fk_KasutajaId = kasutajaID


                    };
                    db.UserItems.Add(userItem);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException e)
            {

                //Log the error (add a variable name after DataException)
                ModelState.AddModelError("", e.ToString());
            }


            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", item.CategoryId);
            return View(item);
        }

        //
        // GET: /Profile/Muuda/5
        public ActionResult Muuda(int id)
        {

            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId =
                new SelectList(db.Categories, "CategoryId", "Name");
            ViewBag.AutorId =
                new SelectList(db.Autors, "AutorId", "Perekonnanimi");
            return View(item);

        }

        //
        // POST: /Profile/Muuda/5
        [HttpPost]
        public ActionResult Muuda(int id, Item item)
        {
            try
            {
                item.ItemId = id;
                var image = WebImage.GetImageFromRequest();
                if (image != null)
                {
                    if (image.Width > 500)
                    {
                        image.Resize(100, ((100 * image.Height) / image.Width));

                    }
                    var filename = Path.GetFileName(image.FileName);
                    image.Save(Server.MapPath("~/UploadedImages/" + filename));
                    filename = Path.Combine("UploadedImages", filename);
                    item.CoverArtUrl = filename;
                }
                if (ModelState.IsValid)
                {


                    db.Entry(item).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {

                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            ViewBag.CategoryId =
               new SelectList(db.Categories, "CategoryId", "Name", item.CategoryId);
            ViewBag.AutorId =
                new SelectList(db.Autors, "AutorId", "Perekonnanimi", item.AutorId);
            return View(item);
        }
        #endregion

        #region KasutajaAndmeteHaldus
        //
        // GET: /LisaAndmed/5
        public ActionResult LisaAndmed()
        {
            return View();
        }

        //
        // POST: /LisaAndmed/5
        [HttpPost]
        public ActionResult LisaAndmed(KasutajaAndmed kasutajaAndmed)
        {
            MembershipUser kasutaja = Membership.GetUser();
            Guid userID = (Guid)kasutaja.ProviderUserKey;
            DateTime nyyd = DateTime.Now;
            if (ModelState.IsValid)
            {
                kasutajaAndmed.Added = nyyd;
                kasutajaAndmed.UserID = userID;
                db.KasutajaAndmed.Add(kasutajaAndmed);
                db.SaveChanges();

                var detailsId = (from x in db.KasutajaAndmed
                                 where x.UserID == userID
                                 select x.Id).FirstOrDefault();

                Kasutaja uusKasutaja = new Kasutaja()
                {
                    fk_KasutajaAndmedId = detailsId,
                    fk_UserId = userID,
                    Added = nyyd,
                    Modified = nyyd,
                    IsActive = true

                };
                db.Kasutajad.Add(uusKasutaja);
                db.SaveChanges();


                return RedirectToAction("Index");
            }
            return View();
        }
        
        [ChildActionOnly]
        public ActionResult UserInfoMenu()
        {
            MembershipUser kasutaja = Membership.GetUser();

            return View(kasutaja);
        }
        //
        // GET: /Andmed/5
        public ActionResult Andmed(Guid userID)
        {
            var tmp = (from x in db.KasutajaAndmed
                       where x.UserID == userID
                       select x.Id).FirstOrDefault();
            var kasutaja = db.KasutajaAndmed.Find(tmp);
            return View(kasutaja);
        }
#endregion

        #region Kaanepiltide mudeli edasi arendus(Nice TO Have)
        // GET: /AddCover
        //public ActionResult addCover(int ItemId)
        //{

        //    return View();

        //}
        //
        // POST: Image
        //public ActionResult addCover(int ItemId, CoverArt cover)
        //{
        //    RaamatuKoguEntities db = new RaamatuKoguEntities();
        //    var raamat = (from x in db.Items
        //                  where x.ItemId == ItemId
        //                  select x).FirstOrDefault();
        //    var image = WebImage.GetImageFromRequest();
        //    if (image != null)
        //    {
        //        if (image.Width > 500)
        //        {
        //            image.Resize(500, ((500 * image.Height) / image.Width));
        //        }

        //        var filename = Path.GetFileName(image.FileName);
        //        image.Save(Path.Combine("../UploadedImages", filename));
        //        filename = Path.Combine("../UploadedImages", filename);

        //        cover.coverArtUrl = Url.Content(filename);

        //        CoverArt pilt = new CoverArt()
        //        {
        //            coverArtUrl = filename,
        //            coverBookTitle = raamat.Title
        //        };

        //        db.CoverArts.Add(pilt);
        //        db.SaveChanges();

        //    }

        //    return View(cover);

        //}
        //
        // GET: /Laenutus/Create
        #endregion

        #region KasutajaLaentuseHaldus
        //
        // GET: /Profile/Laenraamat?itemId=6
        public ActionResult LaenaRaamat(int itemId)
        {
            Item item = db.Items.Find(itemId);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(new Laenutus());
        }

        //
        // POST: /Laenutus/Create

        [HttpPost]
        public ActionResult LaenaRaamat(int itemId, Laenutus laen)
        {
            try
            {
                MembershipUser kasutaja = Membership.GetUser();
                Guid userID = (Guid)kasutaja.ProviderUserKey;
                Item laenutatav = GetItem(itemId);
                if (ModelState.IsValid)
                {
                    DateTime DueDate = laen.Start.AddDays(laenutatav.days);

Release/MvcRaamatuKogu/MvcRaamatuKogu/Views/Shared/UserView.cshtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" 
        rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" 
        rel="stylesheet"  type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" 
        rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")" 
        type="text/javascript"></script>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <h1>
                Library in MVC</h1>
            <p style="float: right; margin: 10px;">
                built with <a href="http://asp.net/mvc">ASP.NET MVC 3</a>
            </p>
            @if (Request.IsAuthenticated)
            {
                <p style="float: right; clear: right; margin-right: 220px;">
                    Logged in as @User.Identity.Name
                </p>
            }
            else
            {
                <p style="float: right; clear: right; margin-right: 220px;">
                    Tere tulemast meie veebipõhisesse Raamatukokku
                </p>
            }
        </div>
        <div id="navigation">
            <ul id="navlist">
                <li class="first"><a href="/" id="current">Kodu</a></li>
                <li>
                    @Html.ActionLink("Raamatukogu", "Index", "Raamatukogu")
                </li>
                <li>
                    @Html.ActionLink("Haldamine", "Index", "RaamatukoguHaldus")
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li>
                        @Html.ActionLink("Minu Profiil", "Index", "Profile")
                    </li>
                }
                else
                {
                    <li>
                        @Html.ActionLink("Logi sisse", "LogOn", "Account")
                    </li>
                }
            </ul>
            @if (Request.IsAuthenticated)
            {
                <div class="logoff">
                    @Html.ActionLink("Logi välja", "LogOff", "Account")
                </div>
            }
        </div>
        <div id="content">
            <div id="left">
                @{Html.RenderAction("UserInfoMenu", "Profile");}
            </div>
            <div id="main">
                @RenderBody()
            </div>
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

Release/MvcRaamatuKogu/MvcRaamatuKogu/Views/Shared/_Layout.cshtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html 
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" 
        rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" 
        rel="stylesheet"  type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.theme.css")" 
        rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery.ui.core.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.ui.datepicker.min.js")" 
        type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/DatePickerReady.js")" 
        type="text/javascript"></script>
</head>
<body>
    <div id="wrapper">
        <div id="header">
            <h1>
                Library in MVC</h1>
            <p style="float: right; margin: 10px;">
                built with <a href="http://asp.net/mvc">ASP.NET MVC 3</a>
            </p>
            @if (Request.IsAuthenticated)
            {
                <p style="float: right; clear: right; margin-right: 220px;">
                    Logged in as @User.Identity.Name
                </p>
            }
            else
            {
                <p style="float: right; clear: right; margin-right: 220px;">
                    Tere tulemast meie veebipõhisesse Raamatukokku
                </p>
            }
        </div>
        <div id="navigation">
            <ul id="navlist">
                <li class="first"><a href="/" id="current">Kodu</a></li>
                <li>
                    @Html.ActionLink("Raamatukogu", "Index", "Raamatukogu")
                </li>
                <li>
                    @Html.ActionLink("Haldamine", "Index", "RaamatukoguHaldus")
                </li>
                @if (Request.IsAuthenticated)
                {
                    <li>
                        @Html.ActionLink("Minu Profiil", "Index", "Profile")
                    </li>
                    

                    
                    
                }
                else
                {
                    <li>
                        @Html.ActionLink("Logi sisse", "LogOn", "Account")
                    </li>
                }
            </ul>
            @if (Request.IsAuthenticated)
            {
                <div class="logoff">
                    @Html.ActionLink("Logi välja", "LogOff", "Account")
                </div>
            }
        </div>
        <div id="content">
            <div id="left">
                <div>
                    @{Html.RenderAction("CategoryMenu", "Raamatukogu");}
                </div>
                <br />
                @if (Request.IsAuthenticated)
                {
                    <div>
                        @{Html.RenderAction("UserInfoMenu", "Profile");}
                    </div>
                }
            </div>
            <div id="main">
                @RenderBody()
            </div>
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>